# Generated by Django 2.2.1 on 2019-05-11 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idea', models.CharField(max_length=255)),
                ('state', models.BooleanField()),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableros', to='usuario.Usuario')),
            ],
        ),
    ]
