# Generated by Django 2.2.1 on 2019-05-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablero',
            name='idea',
        ),
    ]
