# Generated by Django 2.2.1 on 2019-05-12 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('tablero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('state', models.BooleanField()),
                ('tablero_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablero_fk', to='tablero.Tablero')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_fk', to='usuario.Usuario')),
            ],
        ),
    ]
